export const htmlContent = `
<p>HARI ITU&nbsp;,&nbsp;aku&nbsp;mengunjungi aula pelatihan Sword Sanctum, meski kudengar aula itu disebut “Ephemeral Hall” dari semua nama.</p>
<p>Alec ada di sebelah kananku.&nbsp;Ia tersenyum dan tidak menunjukkan sedikit pun rasa permusuhan.&nbsp;Di pinggangnya, ia memegang pedang dua tangan yang ditempa oleh Dewa Bijih dari batu hitam yang kubuat.&nbsp;Pedang itu tidak memiliki kekuatan khusus, tetapi—seperti yang kau duga dari “dewa” dalam nama pembuatnya—pedang itu sangat tajam.&nbsp;Alec menyukai pedang sepanjang hampir dua meter itu dan sekarang membawanya secara teratur.&nbsp;Orsted ada di sebelah kiriku.&nbsp;Ia tetap mengenakan helm hitamnya dan tidak mengatakan sepatah kata pun.&nbsp;Ia berdiri begitu diam sehingga kau mungkin mengira ia adalah potongan foto.&nbsp;Aku setengah berharap seekor lalat akan hinggap di atasnya, tetapi ia begitu menakutkan sehingga nyamuk pun tidak akan berani mencobanya.&nbsp;Orang-orang lain di sini selain kami tidak melihat ke arahku, Alec, atau Orsted.&nbsp;Pandangan mereka semua tertuju pada orang di depanku: Eris.&nbsp;Ia berdiri dengan pedang latihan kayu di tangannya.&nbsp;Ekspresinya serius, dan dia tidak tampak marah, tetapi siapa pun bisa melihat betapa eratnya dia menggenggam pedangnya.</p>
<p>Eris berada di tengah Aula Ephemeral.&nbsp;Di kakinya tergeletak seorang Saint Pedang dengan pergelangan tangan patah.</p>
<p>“Aku menyerah,” gerutu mereka akhirnya.&nbsp;Dengan wajah masam, mereka berdiri dan membungkuk.&nbsp;Tanpa menunggu Eris menjawab, mereka kembali ke sisi aula.</p>
<p>Di sisi aula pelatihan berdiri sebaris prajurit Dewa Pedang, sekitar dua puluh orang.&nbsp;Sungguh dunia yang kecil jika kupikirkan bahwa mereka semua adalah Orang Suci Pedang.&nbsp;Seperti seluruh dunia yang dijejalkan ke dalam ruang yang kecil.</p>
<p>Di seberang Eris duduk seorang pria dan wanita muda.&nbsp;Pria itu mungkin seumuran denganku, meskipun aku tidak tahu pasti.&nbsp;Jika diutarakan seperti itu, aku tidak yakin apakah aku bisa menyebutnya “muda” atau tidak.&nbsp;Namun, banyak Sword Saint berusia tiga puluhan dan empat puluhan, jadi kurasa dia memang termasuk muda.&nbsp;Dia melingkarkan lengannya di sekitar wanita yang duduk di sampingnya, dan dibandingkan dengan Sword Saint, dia tampak santai—bahkan dengan&nbsp;Orsted&nbsp;di depannya.&nbsp;Orsted tetaplah Orsted, bahkan dengan helm yang mengurangi efek kutukan, dan pria ini&nbsp;santai saja&nbsp;.</p>
<p>Tidak ada yang kurang dari Dewa Pedang Gino Britz.&nbsp;Saat dia memancarkan wibawa dengan seorang gadis yang tergantung di lengannya, sulit dipercaya bahwa kami seumuran.&nbsp;Paling tidak, aku tidak akan pernah bisa menghadapi Orsted sambil melingkarkan lenganku di sekitar istriku dan mengusap punggungnya.&nbsp;Aku akan dipukul karena itu—oleh Eris, paling tidak—bagaimanapun juga.&nbsp;Bukannya aku keberatan melihat Eris memukulku saat aku meraih payudaranya sesekali.</p>
<p>Nama wanita itu adalah Nina, dan dia adalah teman Eris yang berpangkat Kaisar Pedang.&nbsp;Namun, dia tidak benar-benar memancarkan energi “Kaisar Pedang”.&nbsp;Sebaliknya, dia bersandar dengan gembira pada suaminya, Gino, dan hanya menepis tangannya setiap kali tangannya bergerak terlalu dekat ke dadanya.&nbsp;Sepertinya mereka bahkan tidak melihat kami.&nbsp;Mereka saling mencintai dengan menjijikkan.</p>
<p>Baiklah, saya harus menjelaskan bagaimana kita bisa berakhir dalam situasi tegang seperti ini.</p>
<p>Sebelumnya di<em>&nbsp;Mushoku Tensei!</em></p>
<p>Ayo kumpul, anak-anak!&nbsp;Namaku Rudeus Greyrat!&nbsp;Mari bersenang-senang!</p>
<p>Hari ini, kami mengunjungi tempat wisata paling populer dan&nbsp;keren&nbsp;di Benua Utara: Sword Sanctum!&nbsp;Memikirkan masa depan, aku perlu berbicara dengan Dewa Pedang, ditambah lagi ada sejarah Eris dengan Dewa Pedang sebelumnya yang harus kuhadapi!&nbsp;Jadi, aku memutuskan untuk pergi memberi penghormatan dan meluruskan keadaan, begitulah.&nbsp;Aku tidak sempat berbicara dengan Dewa Pedang saat ini terakhir kali, jadi ini adalah&nbsp;kunjungan&nbsp;resmiku .</p>
<p>Bersama saya dalam perjalanan itu—tebak saja—Eris!&nbsp;Dari apa yang saya ketahui tentang Jurus Dewa Pedang, para praktisinya cenderung menjadi tipe yang akan mengiris Anda menjadi dua terlebih dahulu dan bertanya kemudian.&nbsp;Saya pikir akan lebih baik untuk membawa sesedikit mungkin penyihir, sama seperti terakhir kali.&nbsp;Saya yakin mereka semua adalah orang-orang yang bermoral baik, tentu saja, tetapi Eris telah membunuh Gall Falion di Kerajaan Biheiril, dan dia adalah ayah mertua Dewa Pedang saat ini!</p>
<p>Bagaimana menurutmu?&nbsp;Setelah itu, bolehkah aku masuk dan meminta bantuannya?</p>
<p>Memang, tergantung suasana di sana, saya siap pulang tanpa menyinggung masalah itu.&nbsp;Apa pun bisa terjadi!&nbsp;Itulah sebabnya saya berencana hanya kami berdua yang pergi.</p>
<p>Setidaknya, itulah rencanaku, tetapi&nbsp;ada kejutan yang mengejutkan.&nbsp;Ketika aku bilang akan menuju ke Sword Sanctum, Orsted bilang dia akan datang dengan aura yang sangat penting.&nbsp;Mungkin&nbsp;dia khawatir aku akan bicara panjang lebar dan membuat Sword God marah.&nbsp;Dengan kata lain, dia akan datang kalau-kalau aku mengacaukannya.&nbsp;Apa pun itu, aku tidak punya alasan untuk menolak, jadi aku setuju.&nbsp;Orsted adalah orang yang menenangkan.</p>
<p>Karena Orsted akan pergi, Alec bersikeras untuk ikut juga.&nbsp;Kau tahu, orang yang terlalu terobsesi untuk menjadi pahlawan, yang telah membuktikan bahwa dia sama buruknya dalam membaca situasi seperti Cliff dulu?&nbsp;Ya, Alec itu!</p>
<p>Secara pribadi, saya ingin berkata, “Maaf, tidak ada orang yang akan membuat masalah.”&nbsp;Saya berterima kasih kepada Alec karena sering menjaga Sieg, tetapi itu masalah lain.</p>
<p>Sir Orsted berkata, “Terserah Anda.”&nbsp;Maka, diputuskanlah.&nbsp;Eris, Orsted, Alec, dan aku akan pergi ke Sword Sanctum bersama-sama.</p>
<p>Jadi kami berangkat!&nbsp;Saat kami tiba, pemandangan desa terpencil yang diselimuti salju menyambut kami.&nbsp;Saya agak gugup, tetapi saya pernah ke sini sebelumnya, dan kali ini, saya ditemani tiga teman yang dapat diandalkan.</p>
<p>“Pemandangan yang luar biasa.&nbsp;Mereka punya banyak pilihan pedang untuk desa terpencil.&nbsp;Oh, aku melihat penduduk desa pertama kita!”</p>
<p>Sambil menggigil di samping teman-temanku yang tabah, aku terus berbicara dengan diriku sendiri hingga kami tiba di aula pelatihan utama Dewa Pedang.</p>
<p>Sekelompok Sword Saint yang tersenyum menunjukkan kami ke Ephemeral Hall.&nbsp;Semua orang ramah, dan suasananya tampak bersahabat.&nbsp;Namun, entah mengapa, ada sensasi geli di tulang belakangku.</p>
<p><em>Itu semua ada di kepala Anda!</em>Aku berkata pada diriku sendiri.<em>&nbsp;Fokuslah pada Dewa Pedang!</em></p>
<p>Tepat saat itu, salah satu Sword Saint berbicara.&nbsp;“Jika tidak apa-apa, pertama-tama aku ingin melihat pedang milik Raja Pedang Berserker Eris yang membunuh mantan Dewa Pedang.”</p>
<p><em>Bagaimana dengan “halo” ini?</em></p>
<p>Sebelum aku sempat berbalik, Dewa Pedang mengangkat bahu.&nbsp;“Terserah kau saja,” katanya.</p>
<p>Setelah itu, semua kekacauan terjadi.</p>
<p>Masih tersenyum tetapi memancarkan permusuhan dari balik mata mereka, para Sword Saint bergerak untuk menantang Eris.&nbsp;Oh, mereka tampak ramah, dan mereka menggunakan pedang latihan, tetapi aku bisa melihat niat jahat mereka.&nbsp;Mereka akan menggunakan pedang kayu itu untuk memukul Eris sampai mati dengan dalih latihan.&nbsp;Sekilas terlihat jelas bahwa mereka tidak akan menahan diri.</p>
<p>Namun, Eris secara teknis masih seorang Dewa Pedang.&nbsp;Butuh lebih dari beberapa Sword Saint untuk mengalahkannya.&nbsp;Dia dengan mudah membalikkan keadaan pada calon penyerangnya.&nbsp;Saat dia mengalahkan satu, lalu yang lain, senyum Sword Saint berubah menjadi geraman penuh kebencian.&nbsp;Mereka tidak lagi menyembunyikan kebencian mereka.&nbsp;Di tengah semua ini, hanya satu orang yang tampak benar-benar tenang—Gino.&nbsp;Bahkan Nina tampak sedikit terganggu oleh pembunuhan di mata Sword Saint, tetapi jelas dari wajah Gino bahwa dia tidak peduli.</p>
<p>Pokoknya, saya berusaha sebisa mungkin untuk memasang wajah ceria dan menjelaskan apa yang sedang terjadi.&nbsp;Demi kebaikan semua orang!</p>
<p><em>Haah.&nbsp;</em><em>Perutku sakit.&nbsp;</em><em>Kok bisa begini?</em></p>
<p>Saya merasa telah mengacau sejak awal.&nbsp;Dengan suasana seperti ini, usaha saya sia-sia.&nbsp;Saya hanya ingin mendapat kesempatan untuk menjelaskan, tetapi kesempatan untuk berbicara sudah hilang sekarang.</p>
<p><em>Aku tidak punya waktu untuk menghentikannya!&nbsp;</em><em>Dia sangat cepat!</em></p>
<p>Serius deh, sebelum Gino selesai berkata, “Terserah kamu,” Eris sudah melangkah maju tanpa ragu, dengan pedang kayu di tangannya.&nbsp;Lebih banyak Sword Saint sedang menunggu di tengah aula pelatihan.&nbsp;Dalam sekejap saat aku menurunkan berat badanku ke tempatku berdiri sekarang, Eris sudah mengalahkan salah satu dari mereka.&nbsp;Kemudian, satu lagi Sword Saint melangkah maju.</p>
<p>“Giliranku!”</p>
<p>“Akulah yang akan kau hadapi selanjutnya!”</p>
<p>Apa ini, whack-a-mole?</p>
<p>Aku merasa sudah waktunya untuk mengakhiri lelucon kecil ini.&nbsp;Ada sekitar dua puluh lebih Sword Saint, dan Eris telah mengalahkan hampir semuanya.&nbsp;Tidak, dia sebenarnya sedang melawan yang terakhir, yang berarti giliran Sword God Gino berikutnya.&nbsp;Untuk saat ini, dia berada di atas segalanya, tetapi jika orang-orangnya disingkirkan, dia tidak punya pilihan selain maju sendiri.&nbsp;Sword Saint mungkin mengantisipasi momen ketika Sword God membunuh pendekar pedang berambut merah itu.&nbsp;Mereka ingin membalas dendam terhadap orang yang telah membunuh mantan Sword God.&nbsp;Mereka pada dasarnya menyatakan bahwa mereka ingin melakukannya.&nbsp;Ini adalah awal dari eksekusi.</p>
<p>Aku menyesali pilihanku.&nbsp;Mungkin datang ke sini adalah ide yang buruk.&nbsp;Bahkan Eris tidak akan lolos dari pertarungan dengan Dewa Pedang tanpa cedera, dan tidak mungkin aku bisa melawannya sendiri dalam jarak ini.&nbsp;Setidaknya semuanya tidak sepenuhnya buruk.&nbsp;Refleksku mungkin terlalu lambat, tetapi Orsted dan Alec akan menghentikan bilah Dewa Pedang untukku.&nbsp;Eris mungkin akan sedikit tergores… tetapi selama dia masih hidup, aku tidak akan mengeluh.&nbsp;Eris siap menghadapi apa pun yang terjadi.&nbsp;Apa pun itu, aku bersyukur mereka ikut bersama kami.</p>
<p>Satu-satunya masalah adalah, jika aku ikut campur dalam duel antara Eris dan Dewa Pedang, negosiasi tidak akan mungkin dilakukan.&nbsp;Aku tidak yakin apa yang akan terjadi… tetapi apa pun itu, aku sudah bisa merasakan sakit perutku.&nbsp;Aku harus menghentikannya, lalu mencari cara untuk membuat kami bisa berbicara.&nbsp;Itulah tugasku di sini.</p>
<p><em>Dengarkan, Rudeus.&nbsp;</em><em>Mereka orang-orang yang mudah marah, tetapi kamu bisa membuat mereka mendengarkan jika kamu benar-benar mencoba berbicara kepada mereka.&nbsp;</em><em>Berikan yang terbaik, kamu dengar?&nbsp;</em><em>Ayo, lawan mereka!</em></p>
<p>“Urgh…aku menyerah.”</p>
<p>Tepat saat itu, Sword Saint terakhir jatuh.&nbsp;Sama seperti yang terakhir, dia mencengkeram pergelangan tangannya.&nbsp;Kalau dipikir-pikir, mereka semua pada dasarnya memegang pergelangan tangan mereka.&nbsp;Bagi sebagian orang, itu tangan kiri, dan bagi sebagian orang lagi tangan kanan, tetapi Eris bahkan tidak repot-repot mengganti teknik.&nbsp;Tidak heran mereka sangat marah.</p>
<p>Apakah Nina yang akan menjadi target selanjutnya?&nbsp;Namun, Nina tampaknya tidak akan bergerak dalam waktu dekat.&nbsp;Aku tidak tahu alasannya, tetapi aku merasa kemungkinan besar itu adalah Dewa Pedang.&nbsp;Saat Dewa Pedang bertindak, saat itulah aku akan bergerak.</p>
<p><em>Perhatikan baik-baik.&nbsp;</em><em>Ini adalah seni Go-no-Sen.&nbsp;</em><em>Begitu Dewa Pedang bangkit, saat itulah aku menyerbu, siap untuk mempermalukan diriku sendiri!&nbsp;</em><em>“Wah, itu benar-benar pertempuran yang spektakuler.&nbsp;</em><em>Aku jadi haus hanya dengan menonton.&nbsp;</em><em>Bagaimana kalau kita berhenti sebentar, minum secangkir teh?”</em></p>
<p>Begitulah caraku masuk.&nbsp;Apakah cukup lancar?&nbsp;Tidak akan terdengar seperti aku mencoba memprovokasinya, bukan?&nbsp;Akan lebih baik jika mengatakan sesuatu yang memuji Sword Saint yang kalah.</p>
<p><em>Ya ampun, kalian di Sword Sanctum benar-benar bersemangat dalam latihan kalian!</em></p>
<p>Ya, saya setuju.&nbsp;Dengan begitu, mereka bisa berkata pada diri sendiri, “Oh, ya, ini latihan.&nbsp;Terkadang Anda kalah.”</p>
<p><em>Oke, oke.&nbsp;</em><em>Ayo.&nbsp;</em><em>Ayo lakukan ini.</em></p>
<p>Ada jeda.&nbsp;Dewa Pedang tidak bergerak, dan Nina juga tidak maju.</p>
<p>“Selesai?”&nbsp;kata Dewa Pedang Gino Britz, nadanya ringan di tengah ketegangan yang berderak.&nbsp;“Sekarang, apa tujuanmu menemuiku?”</p>
<p>Hah?&nbsp;Kedengarannya dia akan mendengarkanku sebelum pertarungan.&nbsp;Itu bukan Jurus Dewa Pedang, tapi cocok untukku.&nbsp;Aku melangkah maju.</p>
<p>“Pertama-tama, saya ingin meminta maaf,” kataku.</p>
<p>“Untuk apa?”&nbsp;​​tanya Gino.</p>
<img src="https://tse3.mm.bing.net/th?id=OIP.EZiUBebn9WThjZ20U-kghQHaLH&pid=Api" alt="cover"/>
<p>“Dewa Pedang sebelumnya.”&nbsp;Saat aku mengatakan ini, ada perubahan di udara di sekitar para Suci Pedang, seolah-olah kita akhirnya mendapatkan apa yang telah mereka tunggu-tunggu.</p>
<p>Dia memberi kita kesempatan!&nbsp;Sekarang saatnya kita!&nbsp;Saatnya balas dendam!&nbsp;Kalau mereka anjing, mereka pasti sudah menggonggong dan siap menerkam.&nbsp;Sesaat, saya bertanya-tanya apakah saya seharusnya bersikap kurang langsung, tetapi semuanya akan berakhir dengan cara yang sama.&nbsp;Tidak ada cara untuk menghindari kebenaran.</p>
<p>Dewa Pedang memasang ekspresi ragu di wajahnya.&nbsp;Melihatnya membuatku ragu juga.&nbsp;Apakah aku mengatakan sesuatu yang aneh?&nbsp;Aku hampir mulai melihat sekeliling dengan gugup.&nbsp;Kemudian, Gino mengangguk dengan ekspresi mengerti.</p>
<p>“Sekarang setelah kau menyebutkannya, Nina pernah mengatakan sesuatu yang lama tentang membantumu, kurasa.&nbsp;Kurasa jika kau membunuh ayah seorang sekutu, kau harus minta maaf, ya?”</p>
<p>Kedengarannya seperti tidak ada hubungannya sama sekali dengan dirinya.&nbsp;Para Sword Saint tampak lebih terkejut daripada aku.</p>
<p>“Tetapi tuanku…yaitu, Dewa Pedang Gall Falion sebelumnya, pergi untuk melawanmu atas kemauannya sendiri, kan?&nbsp;Kalau begitu, bukankah seharusnya kami yang meminta maaf?&nbsp;Jika ini menyangkut seluruh Jurus Dewa Pedang dan dia menyerangmu, maka kamilah yang melanggar perjanjian.&nbsp;Apa yang terjadi dengan itu?&nbsp;Aku tidak tahu apa-apa tentang itu.”</p>
<p>Saya ingin bertanya&nbsp;kepadanya&nbsp;apa yang sedang terjadi.&nbsp;Apakah saya benar-benar sedang berbicara dengan orang teratas dalam Jurus Dewa Pedang saat ini?&nbsp;Saya mengharapkan seseorang yang lebih, Anda tahu, tidak mau mendengarkan alasan, seperti Atofe.&nbsp;Orang ini mungkin&nbsp;terlalu&nbsp;santai.&nbsp;Itu adalah perasaan yang aneh, lebih seperti saya sedang berbicara dengan seseorang dari Jurus Dewa Utara, jika ada.&nbsp;Tentu saja tidak termasuk Atofe.</p>
<p>“Um…”<em>&nbsp;Tenang saja.&nbsp;</em><em>Jawab saja pertanyaannya dulu.</em></p>
<p>“Itu hanya percakapan antara Nina dan Eris—itu terjadi sebelum kesepakatan resmi apa pun tercapai.&nbsp;Sebenarnya aku pernah datang ke sini sebelumnya, tetapi diberi tahu bahwa kau sudah bertunangan, jadi aku pergi lagi… Kupikir Nina akan mengatakannya padamu?”</p>
<p>“Ya,” kata Nina sambil mengangguk samar, “tapi hal itu tidak pernah terjadi lagi sejak saat itu.”</p>
<p>“Mm,” Gino setuju.&nbsp;“Aku belum pernah mendengar apa pun tentang kita yang menentang Dewa Naga Orsted.&nbsp;Meski begitu, jika dia melawanmu…” Mata Gino menyipit.&nbsp;“Kedengarannya seperti pendahuluku menentangmu?”</p>
<p>Semangat para Sword Saint meningkat.&nbsp;Aku hampir bisa mendengar mereka berpikir,&nbsp;Baiklah, kalian mendengarnya!&nbsp;Saatnya menghunus pedang dan bertarung!&nbsp;Ayo, cepat!</p>
<p>“Tunggu,” kataku tergesa-gesa.&nbsp;“Jika kau bisa tenang dulu…”</p>
<p>Gino mengangkat alisnya.&nbsp;“Apakah aku terlihat kesal?”</p>
<p>“Sama sekali tidak!&nbsp;Kau benar-benar gambaran ketenangan!&nbsp;Begini, masalahnya, kami datang ke sini untuk meminta maaf dan memastikan bahwa kau dan aku tidak akan tetap menjadi musuh.&nbsp;Hubungan yang tidak bersahabat dengan para pejuang kuat dari Jurus Dewa Pedang sama sekali bukan yang kami inginkan.&nbsp;Kami ingin bersahabat dengan orang-orang kuat.&nbsp;Kami di sini siap menawarkan persahabatan kepadamu.&nbsp;Kami dapat menawarkan bantuan untuk jalur distribusi pedang dan persediaan makanan, pemeliharaan infrastruktur, dan bahkan konstruksi.&nbsp;Sebaliknya, jika kau menentang kami, kami dapat memutus semua hal itu.&nbsp;Semuanya akan buruk.&nbsp;Benar?”</p>
<p>Setelah aku selesai mengatakan semua ini, Gino mendesah.</p>
<p>Aku mungkin berbicara terlalu lama.&nbsp;Mengingat aku membayangkan Atofe, aku seharusnya mempersingkatnya.&nbsp;Namun, orang ini tidak tampak sesederhana itu hingga dia berbalik dan berkata, “Tentu, aku akan menjadi sekutumu!”&nbsp;hanya karena aku memberinya sebotol anggur yang sangat langka.</p>
<p>Gino menatapku, lalu berbicara.&nbsp;“Apakah aku harus menjelaskannya agar kau mengerti?&nbsp;Pendahuluku tidak mengatakan apa pun kepadaku tentang dendam.&nbsp;Itu berarti keputusannya untuk melawanmu bukan atas nama seluruh Jurus Dewa Pedang—itu masalah pribadi.&nbsp;Itu tidak ada hubungannya dengan kita, jadi aku tidak tertarik untuk bertarung.&nbsp;Ini&nbsp;lebih penting bagiku daripada itu.”</p>
<p>Sambil berkata demikian, dia menarik Nina mendekat dan membenamkan wajahnya di rambut Nina.&nbsp;Pipi Nina memerah, tetapi dia tidak menghentikannya.</p>
<p><em>Aku tahu kau tergila-gila padanya, tapi mungkin sebaiknya kau pertimbangkan untuk tidak melakukannya di depan umum?&nbsp;</em><em>Lihat, Eris merah padam!&nbsp;</em><em>Matanya melotot.</em>Dia juga melipat tangannya dan merentangkan kakinya seolah-olah dia siap bertarung.</p>
<p>Serius deh,&nbsp;ini&nbsp;Dewa Pedang yang sedang kuajak bicara?&nbsp;Jawaban-jawabannya yang cerdas membuatku ketakutan.&nbsp;Itu&nbsp;menyeramkan.&nbsp;Praktisi Jurus Dewa Pedang tingkat tinggi lebih suka berteriak seperti, “Apa sih yang kau bicarakan?&nbsp;Cukup mengoceh!&nbsp;Kau akan mati karena apa yang kau lakukan pada ayahku!”&nbsp;Lalu mereka akan menyerangmu.&nbsp;Benar?&nbsp;Tunggu, lupakan itu.&nbsp;Itu Atofe—jadi, Jurus Dewa Utara.&nbsp;Tapi mereka hampir sama, bukan?</p>
<p>Ada sebuah pikiran.&nbsp;Mungkin orang di depanku ini adalah orang yang mirip, seperti seseorang dari kantor yang bertanggung jawab atas hubungan diplomatik.</p>
<p>Bagaimanapun, aku&nbsp;bersyukur&nbsp;dia merasa seperti itu.&nbsp;Meskipun aneh bahwa dia tidak peduli dengan salah satu kerabatnya yang terbunuh… Kurasa dia sudah mempertimbangkan situasinya dan memutuskan untuk memprioritaskan masa depan daripada perasaannya sendiri.&nbsp;Itu masuk akal bagiku.&nbsp;Aku yakin dia sudah memikirkan semuanya dan mengambil keputusan sejak lama.</p>
<p>“Kalau begitu, izinkan kami untuk—”</p>
<p>“Tahan!”&nbsp;teriak salah satu Sword Saint, sambil berdiri.&nbsp;Wajahnya merah dan menunjuk ke arah kami—bukan, ke arah&nbsp;Orsted.</p>
<p>“Kita semua memuja Dewa Pedang tua!&nbsp;Dengan melihatnya menghunus pedangnya, kita belajar, belajar, dan menjadi lebih kuat!&nbsp;Dan mereka&nbsp;membunuhnya&nbsp;!&nbsp;Orang-orang itu ada di sana!&nbsp;Apakah kita harus tinggal diam?!&nbsp;Mereka membunuh orang yang kita berutang segalanya padanya!&nbsp;Apakah kau ingin membuat Jurus Dewa Pedang menjadi bahan tertawaan?!”</p>
<p>“Baiklah, silakan saja,” kata Gino tanpa ragu.&nbsp;“Ambil pedang sungguhan.&nbsp;Aku akan mengawasimu.”</p>
<p>Pedang Suci itu membeku.&nbsp;“Apa…?”</p>
<p>“Aku yakin mereka datang ke sini siap untuk bertarung.&nbsp;Lihat, itu Raja Pedang Berserker Eris, Dewa Naga Orsted, dan Dewa Utara Kalman III, dengan Rudeus Greyrat di belakang mereka untuk mendukung mereka dengan sihir.&nbsp;Bahkan jika kalian semua menyerang sekaligus, mereka akan menghabisi kalian sebelum kalian mendaratkan satu serangan pun.”</p>
<p>“Tetapi…”</p>
<p>“Ayo, lakukan saja.&nbsp;Aku akan memastikan tubuhmu dirawat dengan baik, dan aku bahkan akan memberimu pemakaman.&nbsp;Aku tidak bisa mengatakan apakah kematianmu akan menjaga kehormatan Jurus Dewa Pedang, tapi aku yakin mayatmu akan puas.”</p>
<p>Dewa Pedang berdiri di sana dalam diam selama beberapa saat setelah ini, lalu duduk kembali, tangannya gemetar karena frustrasi yang tertahan.&nbsp;Kemudian, dia berkata dengan suara gemetar, “Apakah kita… tidak punya pilihan selain mengikuti mereka?&nbsp;Tanpa bertarung, tanpa membalas dendam pada Dewa Pedang lama…”</p>
<p>“Itulah yang kukatakan padamu—kalau kau tidak suka, ambil saja pedangmu.&nbsp;Aku tidak akan memaksakan apa pun pada kalian.&nbsp;Lakukan apa yang kau suka.&nbsp;Sama seperti ayahku dan yang lainnya.”&nbsp;Gino terdengar lelah mendengar ini.</p>
<p>Saya menyukai gagasan untuk segera menenangkan mereka daripada membiarkan dendam berlarut-larut—meskipun tampaknya kejam jika itu menjadi masalah hidup dan mati.</p>
<p>Tepat saat itu, Eris angkat bicara.&nbsp;“Semua Kaisar Pedang sudah pergi, ya?”</p>
<p>Gino menoleh ke arahnya.&nbsp;“Ayahku meninggalkan Sword Sanctum bersama yang lain.&nbsp;Sepertinya mereka tidak senang dengan keputusanku menjadi Sword God.”</p>
<p>Rupanya, “Kaisar Pedang” tidak menyertakan Nina.&nbsp;Frase Gino menunjukkan bahwa ia berbicara tentang dua Kaisar Pedang yang merupakan murid langsung dari Dewa Pedang sebelumnya.&nbsp;Sekarang setelah Eris mengatakannya, aku menyadari bahwa aku tidak dapat melihat siapa pun yang sesuai dengan kriteria itu.</p>
<p>“Aku rasa sekarang, mereka sudah memulai tempat pelatihan mereka sendiri di Asura atau Millis, atau mungkin di Kerajaan Raja Naga.&nbsp;Maksudku, kurasa aku juga bisa pergi.”&nbsp;Gino mengangkat bahu.&nbsp;“Ngomong-ngomong, apakah kau datang hanya untuk meminta maaf?&nbsp;Kau baik hati melakukan itu, tapi sejujurnya aku tidak yakin mengapa kau repot-repot melakukannya.”</p>
<p>Ya ampun.&nbsp;Bukannya mau menjelek-jelekkan siapa pun, tapi Gino agak terlalu—bagaimana ya menjelaskannya?&nbsp;Dingin, filosofis, atau sekadar aneh.</p>
<p>“Tidak, masih ada lagi,” kataku.&nbsp;“Ceritanya panjang, tapi sebenarnya kita sedang melawan makhluk yang disebut Manusia-Dewa…”</p>
<p>Aku memaparkan detail pertarungan antara kami dan Dewa-Manusia.&nbsp;Selain itu, Gino tampak seperti orang yang bisa kuajak bicara.&nbsp;Jika kami bisa mencapai kesepakatan tanpa pertumpahan darah, itu lebih baik!&nbsp;Rasanya antiklimaks, tapi tidak apa-apa.&nbsp;Begitu aku berhenti menatapnya melalui kacamata berwarna Dewa-Pedang, Gino adalah pemuda yang baik dengan kepala yang baik.&nbsp;Setelah mendapatkan kerja samanya, kami bisa duduk untuk minum teh dan saling mengenal lebih baik.&nbsp;Aku yakin dia akan berhenti bersikap menyeramkan saat itu.</p>
<p>“Sebagai penutup,” kataku, “aku ingin secara resmi meminta kerja sama dari Sekolah Dewa Pedang dalam usaha kita di masa depan.”</p>
<p>“Saya menolak.”</p>
<p><em>Kamu…hah?&nbsp;</em><em>Serius?</em></p>
<p>“Saya tidak akan bekerja denganmu.”</p>
<p>Terdengar suara “Ooh!”&nbsp;dari para Sword Saint, tapi mereka tampak sama bingungnya denganku.</p>
<p>“Jadi, kau akan berpihak pada Dewa-Manusia?”&nbsp;tanyaku ragu-ragu.</p>
<p>“Tidak.&nbsp;Aku juga tidak akan melawanmu.”</p>
<p>Oke…?&nbsp;“Maksudmu kau bersikap netral?&nbsp;Bolehkah aku bertanya kenapa?”</p>
<p>“Saya bermaksud untuk tetap setia pada ajaran guru saya.”</p>
<p>“Ajaran apa?”</p>
<p>“Sang guru selalu berkata untuk menjadi kuat demi dirimu sendiri.&nbsp;Sejujurnya, aku tidak mengerti apa maksudnya untuk waktu yang lama.&nbsp;Aku ragu ada orang di sini yang mengerti.&nbsp;Bahkan Kaisar Pedang seperti ayahku tidak mengerti.&nbsp;Ketika aku menyadari bahwa aku menginginkan Nina, semuanya menjadi jelas bagiku.&nbsp;Pedang adalah sesuatu yang kau gunakan untuk dirimu sendiri—murni demi memenuhi tujuanmu sendiri.&nbsp;Tidak ada yang lain.”</p>
<p>Gino berbicara dengan cepat dan lancar, dan ada keyakinan dalam suaranya yang memberitahuku bahwa dia percaya pada kebenaran tak tergoyahkan dari kebijaksanaannya.</p>
<p>“Karena itu,” lanjutnya, “aku tidak akan bekerja sama denganmu.&nbsp;Aku menghunus pedangku untuk diriku sendiri.&nbsp;Semua yang kulakukan, kulakukan untuk diriku sendiri.”</p>
<p>“Sekalipun keluargamu dalam bahaya, kau tidak akan mengangkat pedangmu?”&nbsp;tanyaku.</p>
<p>“Aku akan melakukannya.&nbsp;Jika aku mencintai mereka, aku akan melakukannya,” kata Gino.&nbsp;Kemudian, untuk pertama kalinya, dia menatapku lurus.&nbsp;Tatapannya kuat dan berwibawa, sama sekali tidak seperti gambaran yang digambarkan Eris tentangnya.&nbsp;“Atau apakah kau mengatakan kau akan membunuh keluargaku jika aku menolak bekerja denganmu?”</p>
<p>Hawa dingin menyelimuti aula pelatihan.&nbsp;Suara Gino sedingin es dan nyaris membunuh.&nbsp;Aku merasakan keringat dingin mengucur di sekujur tubuhku.&nbsp;Jika aku sendirian, mungkin aku akan mengompol.&nbsp;Dialah Dewa Pedang, orang yang mengambil gelar itu setelah mengalahkan Dewa Pedang Gall Falion dalam sekejap.&nbsp;Pria yang aneh, ya, tetapi salah satu pendekar pedang terbaik di dunia—kekuatan yang harus diperhitungkan.&nbsp;Aku&nbsp;merasakannya&nbsp;.</p>
<p>“Tidak,” kataku padanya.&nbsp;“Aku juga mencintai keluargaku.”</p>
<p>“Oh?&nbsp;Aku lega mendengarnya.”&nbsp;Nada membunuh itu menghilang dari suaranya.&nbsp;“Sepertinya kau benar-benar seperti yang kudengar, Rudeus.”</p>
<p>“Apa yang orang lain katakan padamu?”</p>
<p>“Bahwa kau menjadi pengikut Dewa Naga demi keluargamu, dan bahwa kau menghancurkan seluruh negara.”</p>
<p>“Eh, itu benar, secara umum.&nbsp;Namun, saya tidak menyia-nyiakan negara mana pun.”</p>
<p>“Kau punya keberanian lebih dari yang kuduga.”&nbsp;Pandangan Gino beralih ke kedua sisiku, ke Eris, Alec, dan para Sword Saint.&nbsp;Mereka semua memegang pedang mereka.&nbsp;Beberapa bahkan sudah menghunus pedang.&nbsp;Aku menoleh ke belakang, tetapi melihat Orsted sama sekali tidak bergerak.&nbsp;Seperti yang kuduga.&nbsp;Aku juga tidak bergerak, tetapi itu hanya karena aku masih terguncang oleh Gino.</p>
<p>“Dengan kata lain, kamu adalah pria yang bisa kupercaya,” lanjut Gino.</p>
<p><em>Apa maksudnya “dengan kata lain”?</em></p>
<p>“Karena kau adalah pria sejati, aku merasa aman untuk mengatakan bahwa aku tidak akan bekerja sama denganmu.&nbsp;Pedangku bertarung untukku dan orang-orang yang kucintai, dan tidak untuk orang lain.”</p>
<p>“Oh… Baiklah.”</p>
<p>Sekarang aku lebih memahami Gino Britz.&nbsp;Dia hanya ingin melindungi orang-orang yang dicintainya dengan tangannya sendiri—tidak seperti diriku.&nbsp;Aku gagal melakukannya dan malah menyerahkan diriku pada belas kasihan Orsted, tetapi aku yakin Gino mengira dia bisa melakukannya.&nbsp;Terlebih lagi, dia tidak salah.&nbsp;Dia hanya tampak tidak termotivasi untuk melakukan hal lain.&nbsp;Tentu saja, dia tetaplah Dewa Pedang; bahkan jika dia menyatakan kenetralannya, itu tidak akan menghentikan musuh untuk mendatanginya, tetapi tampaknya dia tidak memiliki cukup kekuatan untuk membuat lebih banyak lagi.</p>
<p>Aku tidak yakin mengapa dia tidak memasukkan Dewa Pedang sebelumnya ke dalam daftar orang-orang yang dicintainya, tetapi kurasa itu berbeda.&nbsp;Pria itu telah hidup dan mati dengan caranya sendiri.&nbsp;Gino tampaknya tidak keberatan dengan itu.</p>
<p>“Hmm…”</p>
<p>Aku tidak tahu bagaimana lagi aku akan menjual ini padanya.&nbsp;Gino sudah sangat percaya diri.&nbsp;Kecuali jika kami menyerah melawan Dewa-Manusia, atau dia—sepertiku—merasa tidak bisa melindungi keluarganya hanya dengan kekuatannya sendiri, dia tidak akan berubah pikiran.&nbsp;Tidak peduli seberapa keras aku mencoba membujuknya, aku hanya akan mengada-ada.&nbsp;Dia sudah membuat keputusannya dan tidak bisa digoyahkan.&nbsp;Itu seperti yang kau harapkan dari orang paling hebat di sekolah Dewa Pedang.</p>
<p>“Baiklah,” kataku.&nbsp;“Kalau begitu, setidaknya berhati-hatilah jika Dewa Manusia muncul dalam mimpimu.&nbsp;Dia akan berbohong, mengatakan itu semua demi keluargamu, tetapi jika kau mendengarkan, kau akan kehilangan segalanya.”</p>
<p>“Saya mengerti,” kata Gino.</p>
<p>Aku tidak mau, tapi…sudah waktunya untuk mengalah.&nbsp;Gino tidak akan melawan kami, jadi itu sesuatu.&nbsp;Dia tidak akan menjadi sekutu kami, tapi aku juga tidak punya musuh.&nbsp;Setelah mengetahui seperti apa dia, aku percaya padanya bahwa dia cukup percaya padaku untuk jujur.&nbsp;Itu sudah cukup baik bagiku.</p>
<p>“Jika aku meninggal dan orang lain menggantikanku,” Gino menambahkan, “pastikan aku kembali.&nbsp;Ini bukan lebih dari keputusan pribadiku, kau tahu.”</p>
<p>“Terima kasih, saya akan melakukannya.”&nbsp;Saya menoleh ke belakang untuk melihat Orsted.&nbsp;Siapa yang tahu apa yang terjadi di balik helm itu?&nbsp;“Apakah itu cocok untuk Anda, Sir Orsted?”</p>
<p>Dia mengangguk pelan.&nbsp;“Memang begitu.”</p>
<p>Setelah itu selesai dan aku menyembuhkan luka-luka Sword Saints, acara berlanjut ke sesi latihan dengan Alec.&nbsp;Itu berarti aku duduk di depan aula latihan di tempat terhormat, menyaksikan Alec beradu gaya bebas dengan Sword Saints.&nbsp;Sword Saints hanya memiliki pedang latihan, tetapi mereka jelas bertarung untuk membunuh.&nbsp;Aku yakin mereka pikir mereka bisa lolos begitu saja jika mereka membunuh Alec di tengah panasnya latihan.</p>
<p>Alec menepis mereka tanpa kesulitan.&nbsp;Meski begitu, mungkin karena mereka&nbsp;adalah&nbsp;Sword Saint, atau mungkin karena dia sedang teralihkan, beberapa dari mereka kadang-kadang berhasil mengenai dia—dengan Sword of Light.&nbsp;Namun, pada akhirnya, pedang mereka tetap hanya terbuat dari kayu.&nbsp;Saat mereka mengenai, kayunya pecah, dan Alec tidak menerima kerusakan apa pun.&nbsp;Aura pertempuran itu terlalu OP.</p>
<p>Meskipun, mereka menggunakan pedang latihan yang tidak biasa di Sword Sanctum.&nbsp;Tampaknya mereka memiliki inti dari sesuatu seperti besi untuk memberi mereka sesuatu yang mendekati berat yang benar.&nbsp;Tanpa aura pertempuran, serangan di tempat yang salah mungkin sudah cukup untuk membunuh.&nbsp;Hei!&nbsp;Itu menjelaskan mengapa hanya ada Sword Saint di sini.&nbsp;Hanya tingkat lanjut dan di atasnya yang dapat memanggil aura pertempuran.</p>
<p>“Ngomong-ngomong, Sir Orsted, kenapa kau ikut denganku?”&nbsp;bisikku pada Orsted yang ada di sampingku.</p>
<p>“Saya ingin melihat Gino Britz.”</p>
<p>“Maksudmu apa yang berbeda tentang dia dibandingkan biasanya?”</p>
<p>“Memang.”</p>
<p>Gino diam-diam memperhatikan mereka bertarung, dengan Nina di sisinya seperti biasa.&nbsp;Di sampingnya duduk Eris, dan mereka berdua sedang membicarakan sesuatu.&nbsp;Sesekali aku mendengar nama “Gall Falion.”&nbsp;Aku berasumsi mereka sedang membicarakan kematian Dewa Pedang sebelumnya.</p>
<p>“Bagaimana menurutmu?”&nbsp;tanyaku.</p>
<p>“Dia tidak berubah.&nbsp;Dia keras kepala dan bertekad untuk hidup hanya untuk dirinya sendiri.”</p>
<p>“Hah.”</p>
<p>“Saat masih kecil, Gino tidak stabil, mudah terpengaruh oleh kata-kata Dewa Manusia.&nbsp;Nah, dari apa yang kulihat di sini, kita tidak perlu khawatir.”</p>
<p>“Baiklah.”&nbsp;Tergantung bagaimana Anda memikirkannya, pihak netral yang bukan musuh itu seperti sekutu.&nbsp;Itu membuatnya tidak mungkin menjadi murid, untuk satu hal.&nbsp;Dia tidak akan membantu kita mempersiapkan masa depan, tetapi tidak seperti semua negara lain yang mengerahkan seluruh energi mereka untuk itu juga.&nbsp;Yang penting adalah dia tidak akan menjadi pion Dewa-Manusia.&nbsp;Tentu saja, dia mungkin masih akan melawan kita entah dia mau atau tidak… tetapi begitu Anda mulai berpikir seperti itu, tidak ada habisnya.</p>
<p>“A-aku menyerah…!”&nbsp;Terdengar&nbsp;suara keras&nbsp;saat salah satu dari Pedang Suci terjatuh.</p>
<p>“Giliranku selanjutnya!”&nbsp;kata yang lain, langsung berdiri dan menuju ke tengah aula pelatihan…</p>
<p>Hal berikutnya yang kuketahui, semua Sword Saint sedang duduk atau tergeletak di tanah.&nbsp;Setiap Sword Saint terjatuh.&nbsp;Untuk kedua kalinya hari ini.&nbsp;Dewa Utara Kalman III benar-benar hebat, ya?</p>
<p>Ada jeda dalam kebisingan yang memenuhi aula.</p>
<p>“Lalu, tepat di akhir, dia berkata, ‘yang kuat hidup bebas.’”&nbsp;Suara Eris terdengar jelas di tengah keheningan.&nbsp;Dia mendongak, terkejut oleh suaranya sendiri.&nbsp;Mulutnya langsung membentuk garis yang rapat, dan dia melotot mengancam ke arah Sword Saint yang semakin dekat dengannya.</p>
<p>Mereka menunduk, bergumam dan melirik Gino.&nbsp;Aku mendengar komentar seperti “Membuat murid-muridnya bertarung dalam pertempurannya…” dan “Apakah dia peduli dengan kehormatan Jurus Dewa Pedang?”</p>
<p>Ekspresi Gino tampak tidak peduli seperti biasanya.&nbsp;Sejauh yang saya tahu, dia mendengar hal-hal seperti ini setiap hari.</p>
<p>“Maukah kau bergabung dalam latihan kami, Dewa Pedang?”&nbsp;tanya salah satu dari Sword Saint, memanfaatkan kesunyian Gino.&nbsp;Pria itu, yang wajahnya penuh memar, adalah orang yang pertama kali menantang Alec.&nbsp;Dia juga orang yang meminta Gino untuk bertahan sebelumnya.</p>
<p>“Tidak.&nbsp;Aku baik-baik saja di sini,” jawab Gino.</p>
<p>“Mengapa?!”</p>
<p>“Kenapa aku harus melakukannya?&nbsp;Aku meminta dia berlatih denganmu karena kamu yang memintaku.&nbsp;Kalau kalian semua sudah merasa cukup, ya sudah.”</p>
<p>Wajah Orang Suci Pedang berubah, dan dia gemetar karena marah.&nbsp;Tidak tahan lagi, dia berteriak, “Situasi lebih baik dengan Dewa Pedang yang lama!&nbsp;Dia menjunjung tinggi kehormatan Jurus Dewa Pedang!&nbsp;Dia tidak akan membiarkan mereka masuk ke sini, tidak peduli siapa mereka!&nbsp;Tidak heran Kaisar Pedang pergi!&nbsp;Kamu adalah Dewa Pedang, tetapi kamu bahkan tidak akan mengajari kami keterampilanmu!&nbsp;Kamu menyelinap pergi sendirian untuk melakukan semua pelatihanmu, lalu duduk di aula pelatihan menggoda wanitamu&nbsp;hari&nbsp;demi hari!&nbsp;Hal yang sama terjadi di sini, dengan orang-orang ini.&nbsp;Kamu seharusnya membalas dendam sendiri, tetapi sebaliknya kamu menghibur mereka sementara mereka memintamu untuk menjadi pelayan mereka!&nbsp;Jika kamu menelan harga dirimu dan tunduk pada musuh yang lebih kuat, itu akan tetap lebih baik dari ini!&nbsp;Sebaliknya, kamu membuat pernyataan netralitas setengah matang&nbsp;?!&nbsp;Apakah kamu ingin membuat musuh bagi kami, pengikutmu?&nbsp;Apa yang&nbsp;salah&nbsp;denganmu?!&nbsp;Apa gunanya Dewa Pedang sepertimu?!”</p>
<p>Suasana hening menyelimuti aula pelatihan.&nbsp;Ekspresi Gino tidak berubah.&nbsp;Ia tampak tidak peduli seperti sebelumnya—bahkan kosong.&nbsp;Seolah bertanya-tanya apa yang sedang dibicarakan orang ini.</p>
<p>Sebaliknya, lelaki itu menjadi pucat, seolah dia tahu bahwa dia telah berbicara terlalu banyak.</p>
<p>“Setiap orang punya pedangnya sendiri.&nbsp;Kemenanganku bukanlah kemenangan untukmu, dan itu juga tidak akan menjunjung tinggi kehormatanmu,” kata Gino lembut.&nbsp;“Aku mengalahkan Dewa Pedang terakhir karena aku menginginkan apa yang Nina dan aku miliki sekarang.&nbsp;Itulah sebabnya aku bertindak seperti ini.&nbsp;Aku tidak melakukannya untuk menjunjung tinggi kehormatan siapa pun, dan aku tidak melakukannya karena aku ingin menjadi pengasuhmu.&nbsp;Jika kamu tidak menyukainya, kamu bebas pergi.&nbsp;Aku tidak keberatan mengundurkan diri sebagai Dewa Pedang, tetapi jika aku menyerahkan gelar itu kepadamu, kamu akan mengusirku, bukan?&nbsp;Aku tidak keberatan untuk pergi, tetapi saat ini adalah waktu yang buruk bagiku, sementara anak-anak kita masih sangat kecil.”</p>
<p>Terdengar desahan dari para Sword Saint saat mereka melihat ke lantai lagi.&nbsp;Aku setengah berharap seseorang akan berteriak, “Bukan itu masalahnya!&nbsp;Kenapa kalian tidak bisa mengerti?!”&nbsp;Energi di aula itu mengerikan.&nbsp;Rupanya, hubungan antara Sword God dan murid-muridnya tidak berjalan baik.&nbsp;Apakah karena Gino sendiri masih muda?&nbsp;Jika dia tidak menyelesaikan masalah dengan orang-orang ini, dia bisa dengan mudah dikelilingi oleh musuh.</p>
<p>“Tidak perlu seperti itu.&nbsp;Setidaknya kau bisa memberi mereka pertunjukan.”&nbsp;Nina-lah yang memecah keheningan.&nbsp;Ia mengangkat kepalanya dari bahu Gino, duduk tegak, dan menyelipkan kakinya di bawahnya.&nbsp;“Aku ingin melihatmu bertarung juga,” katanya.</p>
<p>“Baiklah!&nbsp;Hanya untukmu, Nina.”&nbsp;Begitu saja, Gino berdiri, seolah-olah semua keengganannya selama ini hanyalah sandiwara.&nbsp;Apakah Nina telah&nbsp;mencambuknya&nbsp;?&nbsp;Lebih tepatnya, jika dia bisa berubah seperti itu, apakah dia benar-benar stabil?&nbsp;Bagiku, setidaknya, dia tampak tidak stabil.&nbsp;Apakah pria ini&nbsp;baik-baik saja&nbsp;?</p>
<p>“Bagaimana denganmu, Eris?”&nbsp;kata Nina.&nbsp;“Gino lebih kuat dari sebelumnya.”</p>
<p>Sebagai tanggapan, Eris juga berdiri.&nbsp;“Baiklah,” katanya.&nbsp;Dia menatapku, lalu melemparkan sesuatu.&nbsp;Aku menangkapnya tanpa berpikir, lalu melihat bahwa itu adalah pedangnya—pedang ajaib Windpipe.&nbsp;Itu adalah pedang yang digunakan oleh Dewa Pedang sebelumnya.</p>
<p>Gino dan Eris pindah ke tengah aula pelatihan, tempat Alec berdiri.</p>
<p>Dia mengangkat bahu.&nbsp;“Baiklah, siapa yang harus kulawan pertama?”</p>
<p>“Yang lebih lemah, tentu saja,” kata Eris, mendorong Alec kembali.&nbsp;Dia mengangguk tanda setuju, lalu kembali menghampiri kami.&nbsp;Tidak ada setetes keringat pun di tubuhnya.&nbsp;Aku tidak pernah melihatnya berkeringat, bahkan… Tunggu, itu tidak benar.&nbsp;Di Kerajaan Biheiril, aku pernah melihatnya basah kuyup.</p>
<p>“Dasar orang-orang yang tidak berguna,” bisiknya sambil duduk di sampingku.&nbsp;“Di sini mereka punya kesempatan untuk belajar dari orang-orang yang lebih baik dari mereka, tetapi mereka tidak tertarik untuk belajar.”</p>
<p>“Ya, bahkan aku bisa melihatnya.”</p>
<p>“Benar?&nbsp;Mereka bahkan lebih buruk dari geng yang nongkrong di dekat nenekku.”</p>
<p>Agar adil, situasinya sedikit berbeda bagi pengawal pribadi Atofe.&nbsp;Bagi mereka, yang penting adalah belajar atau mati, jadi mereka tidak punya pilihan selain menjadi lebih kuat.</p>
<p>Dengan pikiran itu, aku mendongak tepat pada waktunya untuk melihat Eris mengangkat pedang kayunya.&nbsp;Seperti biasa, dia mengangkatnya di atas kepalanya dalam posisi menyerang.&nbsp;Dewa Pedang Gino menjatuhkan diri di atas kaki belakangnya, tangannya di atas pedangnya.&nbsp;Posisi itu mengingatkanku pada Ghislaine, tetapi Gino jauh lebih tenang.&nbsp;Ketika Ghislaine mengambil posisi itu, dia mengibaskan ekornya dengan kilatan menakutkan di matanya, seperti dia sedang menunggu saat yang tepat untuk menancapkan giginya ke mangsanya.&nbsp;Sementara itu, Gino kosong.&nbsp;Seperti Orsted sebelumnya, dia begitu diam seolah-olah waktu telah berhenti.&nbsp;Tidak ada yang bisa melewatinya.</p>
<p>Eris perlahan mendekatinya.&nbsp;Kalau saja percakapan kami sebelumnya tidak terjadi, jantungku pasti berdebar kencang.&nbsp;Dia mungkin akan memukulnya, tetapi dia tidak akan&nbsp;mati.</p>
<p>Ini&nbsp;akan&nbsp;baik-baik saja, kan?</p>
<p>Mungkin aku harus membuka Mata Kejelianku, untuk berjaga-jaga.&nbsp;Namun, bahkan dengan mata iblis, aku tetap tidak akan bisa melihat gerakan pedangnya.&nbsp;Bisakah aku mengandalkan Orsted untuk menghentikannya jika dia hendak melancarkan serangan mematikan?</p>
<p>“Aku berasumsi kau tidak memerlukan sinyal start?”&nbsp;Gino bertanya pada Eris.</p>
<p>“Tidak,” katanya.</p>
<p>Dan kemudian, semuanya berakhir.</p>
<p><em>Eris menerima pukulan di tangan pedangnya dan berlutut.&nbsp;</em><em>Pedang kayunya berputar di udara dan menghantam dinding aula pelatihan dengan bunyi gemerincing.</em></p>
<p>Hanya itu yang berhasil kulihat dengan mata iblis sebelum, tak lama kemudian, itu menjadi kenyataan.&nbsp;Bagiku, sepertinya Eris bergerak lebih dulu.&nbsp;Sebelum dia selesai berkata “Tidak,” ujung pedangnya sudah kabur, tapi dia sudah kalah.&nbsp;Gino lebih cepat, dan serangannya telah mematahkan lengan pedangnya.&nbsp;Kecuali, itu bukan hanya lengan pedangnya.&nbsp;Jempol kaki depan Eris tertekuk ke arah yang salah.&nbsp;Jadi dia menyerang dua kali?&nbsp;Serangan multi-hit?</p>
<p>Lengan dan jari kaki Eris patah, tetapi dia tidak menyerah.&nbsp;Butuh lebih dari itu untuk menghentikannya.&nbsp;Dia menyerang maju dengan satu kakinya yang masih sehat, dengan seringai ganas di wajahnya… lalu, tiba-tiba, dia rileks dan menyerah.</p>
<p>“Cukup,” kata Orsted, suaranya menggema di seluruh aula.&nbsp;Mendengar ini, orang-orang mulai berseru kagum “Ooh” dan mengatakan hal-hal seperti “Luar biasa!”&nbsp;Namun, mereka adalah minoritas, dan bahkan saat itu, suara mereka mengandung nada kebingungan.</p>
<p>Para Suci Pedang berbisik-bisik di antara mereka.</p>
<p>“Apa yang terjadi?&nbsp;Apakah dia berhasil menghindari serangan pertama?”</p>
<p>“Dia menyerang pergelangan kakinya terlebih dahulu.&nbsp;Dia tidak sepenuhnya menghindarinya, jadi jari kakinya…”</p>
<p>“Tapi bagaimana dengan serangan kedua?”</p>
<p>Itu berakhir begitu cepat sehingga mereka tidak dapat mengatakan siapa pemenangnya, tetapi itu jelas sekilas.&nbsp;Eris jatuh ke tanah, keringat bercucuran darinya, sementara Dewa Pedang, yang masih berdiri, dengan lesu menurunkan pedangnya.&nbsp;Gino telah menyetujui permintaan para Orang Suci Pedang untuk demonstrasi, tetapi mereka bahkan tidak dapat mengetahui apa yang telah dilakukannya.&nbsp;Apa gunanya?&nbsp;Mungkin frustrasi dengan hal ini, wajah para Orang Suci Pedang menjadi dingin.&nbsp;Di balik itu, aku melihat sedikit kelegaan.&nbsp;Kehormatan sekolah Dewa Pedang aman.&nbsp;Jika ego mereka terpuaskan, maka itu adalah kemenangan bagiku.</p>
<p>“Hebat, Dewa Pedang!”&nbsp;kata Alec agak terlalu keras.&nbsp;“Serangan pertamamu ditujukan ke pergelangan kakinya, tetapi kemudian kau mengayunkan pedangmu ke atas sepanjang jalur terpendek yang mungkin untuk mengenai pergelangan tangannya.&nbsp;Tidak masalah apakah kau mengenai pergelangan kakinya atau dia menghindar.&nbsp;Apa pun itu, kau menunda serangan pertamanya cukup lama sehingga kau menciptakan celah di pergelangan tangannya tempat kau bisa melawan.&nbsp;Hanya seorang petarung yang sangat yakin dengan kecepatan pedangnya yang bisa melakukan hal seperti itu!”</p>
<p>Kedengarannya seperti dia mendengar kebingungan para Sword Saint.&nbsp;Mereka mengangguk dan berkata, “Ah, sekarang aku mengerti.”</p>
<p><em>Terima kasih atas komentarnya, Alec.</em></p>
<p>Alec tetap duduk, tetapi ada sedikit rasa celaan di matanya saat ia menatap Gino.&nbsp;Pandangan itu berkata,&nbsp;Kau adalah guru mereka.&nbsp;Kau harus mengajari mereka.</p>
<p>“Dulu, kamu tetap akan menyerangku, bahkan dalam kondisi seperti itu,” kata Gino.</p>
<p>“Jika ini saatnya aku teguh pada pendirianku, aku akan tetap berjuang,” jawab Eris.</p>
<p>“Kau benar-benar hebat, Eris.”&nbsp;Sambil tersenyum tipis, Gino mengangguk pelan.</p>
<p>Sebagai tanggapan, Eris tertawa, tetapi ada butiran keringat di alisnya.&nbsp;Pergelangan tangan atau pergelangan kaki yang patah tidak cukup untuk membuat Eris menangis, tetapi tetap saja pasti sakit.&nbsp;Aku berdiri dan berlari menghampirinya.</p>
<p>“Kau baik-baik saja?”&nbsp;tanyaku.</p>
<p>“Ya,” katanya perlahan.&nbsp;“Aku baik-baik saja.&nbsp;Cepat sembuhkan aku.&nbsp;Tapi&nbsp;jangan&nbsp;coba-coba menyentuh apa pun!&nbsp;Kita di tempat umum.”</p>
<p>“Ya, Bu.”</p>
<p>Aku segera merapal mantra penyembuhan untuk menyembuhkan tulang Eris yang patah.&nbsp;Karena aku sudah diperingatkan, aku tidak mencoba untuk merasakannya.&nbsp;Meskipun ini adalah pertarungan pura-pura, Gino telah memukul cukup keras hingga mematahkan tulang.&nbsp;Aku bergidik membayangkan apa yang akan terjadi jika dia memukul kepala atau lehernya.&nbsp;Setidaknya Orsted ada di sini, jadi selama dia tidak benar-benar memenggal kepalanya dari bahunya, tidak ada kerusakan permanen yang terjadi.</p>
<p>Dewa Pedang memang hebat.&nbsp;Aku belum pernah melihat pedangnya bergerak sama sekali, sama seperti pendahulunya.&nbsp;Aku tidak ingin orang ini menjadi musuhku.</p>
<p>“Bagaimana?”&nbsp;tanyaku pada Eris.</p>
<p>“Dia sangat hebat.&nbsp;Aku benci mengatakannya, tapi aku tidak pernah punya kesempatan.”&nbsp;Aku sudah bertanya tentang luka-lukanya, tapi itulah jawaban yang kudapat.&nbsp;Dia terdengar sangat menyesal dan dia mengerutkan kening.&nbsp;Menjadi seorang ibu tidak membuat Eris kurang serius dalam latihan pedangnya.&nbsp;Dalam konteks itu, dia—oh, siapa yang kubohongi?&nbsp;Dia hanya frustrasi karena dia kalah.&nbsp;Eris selalu benci kalah.</p>
<p>“Kalau begitu, sekarang giliranku.”</p>
<p>Saat aku menuntun Eris kembali, Alec berdiri, wajahnya berseri-seri karena kegembiraan—tetapi sebelum dia bisa bergegas masuk, dia kembali menoleh ke arah Orsted.</p>
<p>“Tuan Orsted, bolehkah saya?”</p>
<p>“Sesuai keinginanmu.”</p>
<p>Apakah Orsted memberinya izin untuk menghajar Gino habis-habisan?&nbsp;Itu bisa mengubah tatanan Tujuh Kekuatan Besar.&nbsp;Gino telah menyatakan kenetralannya, dan kekalahan Eris barusan telah memuaskan ego para Sword Saint.&nbsp;Sampai sekarang, Sword Sanctum bersikap netral.&nbsp;Jika Sword God kalah, persamaannya berubah.&nbsp;Bukan hanya Gino, tetapi sebagian besar Sword Sanctum mungkin akan melawan kita.&nbsp;Ini sulit.&nbsp;Haruskah aku menghentikannya?</p>
<p>Tidak!&nbsp;Aku tidak bisa berkata apa-apa, tidak setelah Orsted memberikan lampu hijau.&nbsp;Yang bisa kulakukan hanyalah memikirkan cara memperbaikinya jika terjadi kesalahan.</p>
<p>“En garde!”&nbsp;Alec melangkah maju.&nbsp;Ini adalah pertarungan tiruan dengan pedang kayu, tetapi para petarungnya tetaplah Dewa Utara dan Dewa Pedang.&nbsp;Tidak berlebihan jika menyebutnya pertarungan antara Kekuatan Besar.&nbsp;Tujuh hanyalah angka acak.&nbsp;Siapa yang akan menang?</p>
<p>Dari segi pengalaman, Alec lebih unggul.&nbsp;Dewa Pedang telah mengalahkan pendahulunya, tetapi dia masih muda.&nbsp;Dia belum cukup banyak melakukan sesuatu.&nbsp;Dan Alec memiliki harga dirinya sebagai Dewa Utara Kalman III.&nbsp;Dia juga telah melihat lawannya dan dapat mengikuti gerakannya.</p>
<p>Alec berdiri dengan pedang teracung di depannya.&nbsp;Gino menjatuhkan diri di atas kaki belakangnya.&nbsp;Siapa yang akan bergerak lebih dulu?&nbsp;Biasanya, Anda akan mengira Gino, petarung Jurus Dewa Pedang, akan menyerang, dan petarung Jurus Dewa Utara akan melawan.&nbsp;Namun saya merasa yang sebaliknya bisa saja terjadi.</p>
<p>Alec-lah yang bergerak pertama.</p>
<p>Kali ini, aku melihatnya: sebuah tusukan dari tengah, bergerak begitu cepat sehingga seperti tidak ada gerakan daripada gerakan lambat.&nbsp;Pedang Gino bahkan lebih cepat.&nbsp;Dia mengatur waktu tebasannya dengan sempurna untuk bertemu dengan ujung tusukan Alec, menangkisnya beberapa derajat saja… dan hanya itu yang kulihat.&nbsp;Hal berikutnya yang kuketahui, pedang Gino telah lenyap.&nbsp;Sesaat kemudian, aku melihat tangan kiri Alec terkulai lemas dan patah.&nbsp;Bersamaan dengan itu, Alec melangkah mundur.&nbsp;Sebuah garis hitam tetap berada di lantai aula pelatihan tempat dia berdiri.&nbsp;Gino pasti telah menggunakan serangan bersamaan yang sama yang digunakannya untuk mengalahkan Eris, tetapi kali ini mengenai pergelangan tangan terlebih dahulu.</p>
<p><img decoding="async" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEios2G_5wq1BBgYUFU8iV96rccnvLWQlhp34tBhnEb07kUTRUofrmWAFc5lXGiELkHX01Rj3KPoFR83W8lkX_K-Vp9NBEn4R7xTPWGpWPT1KXfb5Pvjam5gx81apKpWbQwiZ9DFKUwpO7zJJRa8lnmbCWTpxNI2nulGLjXkTheV96XIZ6xJG2iXxzMmNCOQ/s2000/image033.jpg"></p>
<p>Alec menyesuaikan pegangannya pada pedang dengan tangannya yang patah.&nbsp;Yah, kukira&nbsp;pedangnya&nbsp;patah, tetapi pedangnya sembuh hampir seketika.&nbsp;Itulah darah iblisnya yang abadi.&nbsp;Ada api di matanya yang seolah berkata, “Dalam Jurus Dewa Utara, di sinilah pertarungan sesungguhnya dimulai.”</p>
<p>Gino melangkah maju dan melancarkan serangan yang ganas.&nbsp;Dengan setiap ayunan pedangnya, ia mematahkan salah satu lengan atau kaki Alec.&nbsp;Alec tidak butuh waktu lebih dari sekejap untuk pulih, jadi serangan itu tidak melumpuhkannya, tetapi itu satu-satunya keuntungan.&nbsp;Alec mungkin mencoba banyak gerakan, tetapi tidak ada yang membuat lawannya gentar.&nbsp;Gino tidak memberi satu pun peluang bagi Alec untuk menyerang.</p>
<p>Akhirnya, Alec menurunkan pedangnya dan berkata, “Aku menyerah.”</p>
<p>Dia tidak terluka, tetapi pakaiannya compang-camping, dan ujung pedang kayunya terbelah.&nbsp;Sementara itu, Gino tidak terluka.&nbsp;Dia basah oleh keringat, tetapi itu tetap merupakan kemenangan yang luar biasa.&nbsp;Aku tidak menyangka akan ada celah yang begitu lebar, apalagi melawan lawan sekuat Alec.&nbsp;Gino bisa saja menyaingi Kekuatan Besar—tunggu, lupakan itu.&nbsp;Dia&nbsp;sudah&nbsp;menjadi salah satu Kekuatan Besar.</p>
<p>“Ya ampun, kamu kuat!”&nbsp;seru Alec.&nbsp;“Ini menjadi pengingat bahwa sekuat apa pun dirimu, akan selalu ada orang yang lebih kuat.”</p>
<p>“Ah, tapi kamu bertarung dengan satu tangan.&nbsp;Siapa tahu apa yang akan terjadi dalam pertempuran sesungguhnya?”</p>
<p>“Jika ini benar-benar pertarungan, kurasa aku akan hancur berkeping-keping,” kata Alec, dengan lapang dada menerima kekalahannya.</p>
<p>Itulah yang bisa dilakukan Dewa Pedang dengan pedang latihan tanpa sarung.&nbsp;Dengan pedang sungguhan, dia akan lebih cepat.&nbsp;Jarak di antara mereka mungkin akan lebih besar.</p>
<p>“Benar.”&nbsp;Masih menggenggam pedang kayunya, Alec kembali ke tempat kami duduk.&nbsp;Meskipun kalah, ekspresinya cerah.&nbsp;Ada sedikit kekecewaan di sana, tetapi tidak seperti saat ia berteriak dan menangis di Kerajaan Biheiril.&nbsp;Kurasa ia juga sudah tumbuh.</p>
<p>“Hm?”&nbsp;Aku melirik dan melihat semua mata di aula pelatihan tertuju padaku.&nbsp;Meskipun pertarungan telah berakhir, Gino masih berada di tengah aula.&nbsp;Dia juga memperhatikanku.</p>
<p>Aku mendengar para Suci Pedang berbicara dengan suara pelan.</p>
<p>“Kekuatan Besar Ketujuh…”</p>
<p>“Kita akan menyaksikan pertarungan antara dua kekuatan besar!”</p>
<p>“Tentu saja, bukan berarti Dewa Pedang akan kalah.”</p>
<p>“Kita bahkan mungkin bisa melihat sebagian kekuatan Dewa Naga Orsted.”</p>
<p><em>Apa?&nbsp;</em><em>Hah?&nbsp;</em><em>Sekarang bagaimana?</em></p>
<p>“Tuan Rudeus,” bisik Alec di telingaku, “dengan cara apa pun, tunjukkan kepada mereka kekuatan Armor Ajaib yang kau gunakan untuk mengalahkanku!”</p>
<p>Mendengar itu, aku langsung menjawab.&nbsp;Aku sudah menyiapkan pidatoku.</p>
<p>“Ya ampun, kamu di Sword Sanctum benar-benar bersemangat dengan latihanmu!&nbsp;Tapi lihatlah itu?&nbsp;Matahari hampir terbenam, dan aku kelaparan!&nbsp;Bagaimana kalau kita selesaikan semuanya di sini?!”</p>
<p>Itu tidak berjalan dengan baik.</p>
<p>&nbsp;</p>
<p>Aku mengakhiri kunjunganku ke Sword Sanctum.&nbsp;Semua Sword Saint menganggapku pengecut, tapi apa peduliku?&nbsp;Sword Sanctum—atau, lebih tepatnya, Gino Britz—akan tetap netral selama dia hidup.&nbsp;Itu sudah cukup bagiku.</p>
<p>&nbsp;</p>
            </div>
`;